[connections.my_database]
    type="sql"
    dialect="postgres"
    username="postgres"
    password="admin"
    host="localhost" # IP or URL
    port=5432 # Port number
    database="crm" # Database name